# Use the official Nginx image as a base
FROM nginx:alpine

# Set the working directory
WORKDIR /usr/share/nginx/html

# Copy your UI files into the container
COPY ./dist /usr/share/nginx/html

# Copy your Nginx configuration file
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy SSL certificates into the container (optional if you are using Let's Encrypt)
#COPY /etc/letsencrypt/live/starteryou.com-002/fullchain1.pem /etc/ssl/certs/fullchain.pem
#COPY /etc/letsencrypt/live/starteryou.com-002/privkey1.pem /etc/ssl/private/privkey.pem

# Expose port 80 and 443
EXPOSE 80 443

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
