const mongoose = require("mongoose");

/**
 * Schema for storing text content for different pages and components.
 *
 * @typedef {Object} TextContent
 * @property {string} page - The name of the page to which the content belongs.
 * @property {string} component - The name of the component on the page.
 * @property {string} content - The main content of the component.
 * @property {string[]} paragraphs - An array of paragraphs for the content.
 * @property {Date} createdAt - Timestamp when the document was created. (Auto-generated by Mongoose)
 * @property {Date} updatedAt - Timestamp when the document was last updated. (Auto-generated by Mongoose)
 */

/**
 * Mongoose schema for storing text content on a page/component.
 *
 * @type {mongoose.Schema}
 */
const textContentSchema = new mongoose.Schema(
  {
    page: {
      type: String,
      required: true,
    },
    component: {
      type: String,
      required: true,
    },
    content: {
      type: String,
      required: true,
      default: "",
    },
    paragraphs: {
      type: [String],
      default: [],
    },
  },
  { timestamps: true }
);

// Add an index for efficient querying by page and component
textContentSchema.index({ page: 1, component: 1 });

/**
 * Model for TextContent.
 *
 * @type {mongoose.Model<TextContent>}
 */
module.exports = mongoose.model("TextContent", textContentSchema);
