name: Auto PR from develop to Main

on:
  push:
    branches:
      - develop

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: develop
          title: "🚀 Promote develop to Main"
          body: "This PR promotes the latest changes from `develop` to `main`."
          labels: "auto-pr"
          assignees: "your-github-username"
